use super::*;

impl ProfileManager {
    #[cfg(target_os = "windows")]
    pub fn generate_aliases(&self) -> Result<String> {
        let profiles = self.list_profiles()?;
        // Always sync — even when empty (cleans up stale .cmd files)
        let cmd_report = self.sync_cmd_aliases()?;
        if profiles.is_empty() {
            return Ok(format!(
                "# No profiles found. Add one with: cswitch add <name>\n\n{}",
                cmd_report
            ));
        }
        let ps = self.generate_powershell_aliases(&profiles)?;
        Ok(format!("{}\n\n{}", ps, cmd_report))
    }

    #[cfg(not(target_os = "windows"))]
    pub fn generate_aliases(&self) -> Result<String> {
        let profiles = self.list_profiles()?;
        if profiles.is_empty() {
            return Ok("# No profiles found. Add one with: cswitch add <name>".to_string());
        }
        // If ~/.varusers/bin exists, sync self-contained shell scripts there.
        // Otherwise fall back to bash-aliases / bashrc.d.
        if let Ok(bin) = Self::sh_bin_dir() {
            if bin.exists() && bin.is_dir() {
                let report = self.sync_sh_scripts()?;
                return Ok(format!(
                    "# Shell scripts synced to {}\n{}",
                    bin.display(),
                    report
                ));
            }
        }
        self.generate_shell_aliases_with_bashrc_d(&profiles)
    }

    #[cfg(not(target_os = "windows"))]
    pub(super) fn generate_shell_aliases_with_bashrc_d(
        &self,
        profiles: &[Profile],
    ) -> Result<String> {
        let aliases_content = self.generate_shell_aliases(profiles)?;
        let home = Self::home_dir()?;
        let bashrc_d = home.join(".bashrc.d");

        if bashrc_d.exists() && bashrc_d.is_dir() {
            fs::create_dir_all(&bashrc_d)?;
            let alias_file = bashrc_d.join("38-claude-switch.sh");
            fs::write(&alias_file, &aliases_content)?;
            Ok(format!(
                "{}\n\n# Aliases written to: ~/.bashrc.d/38-claude-switch.sh",
                aliases_content
            ))
        } else {
            Ok(aliases_content)
        }
    }

    #[cfg(not(target_os = "windows"))]
    pub(super) fn generate_shell_aliases(&self, profiles: &[Profile]) -> Result<String> {
        let mut lines = vec![
            "# claude-switch aliases — auto-generated by `cswitch aliases`".to_string(),
            String::new(),
        ];
        for p in profiles {
            if p.kind == ProfileKind::Lightweight {
                lines.push(format!(
                    "# Profile '{}' (lightweight): use 'cswitch use {}'",
                    p.name, p.name
                ));
                continue;
            }
            let dir = self.profile_dir(p);
            let alias_name = p.alias.as_deref().unwrap_or(&p.name);
            lines.push(format!(
                "alias claude-{}=\"CLAUDE_CONFIG_DIR='{}' claude\"",
                alias_name,
                dir.display(),
            ));
        }
        Ok(lines.join("\n"))
    }

    pub(super) fn generate_powershell_aliases(&self, profiles: &[Profile]) -> Result<String> {
        let mut lines = vec![
            "# claude-switch aliases — add to your PowerShell profile".to_string(),
            "# Run: notepad $PROFILE  to edit your profile".to_string(),
            "# Generated by: cswitch aliases".to_string(),
            String::new(),
        ];
        for p in profiles {
            if p.kind == ProfileKind::Lightweight {
                lines.push(format!(
                    "# Profile '{}' (lightweight): set env vars before running claude",
                    p.name
                ));
                continue;
            }
            let dir = self.profile_dir(p);
            let alias_name = p.alias.as_deref().unwrap_or(&p.name);
            lines.push(format!(
                "function claude-{} {{ $env:CLAUDE_CONFIG_DIR='{}'; claude @args }}",
                alias_name,
                dir.display(),
            ));
        }
        Ok(lines.join("\n"))
    }
}
