use anyhow::{bail, Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;

// ── Data types ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ProfileKind {
    Lightweight,
    Full,
}

impl Default for ProfileKind {
    fn default() -> Self {
        ProfileKind::Full
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LightweightEnv {
    pub auth_token: Option<String>,
    pub base_url: Option<String>,
    pub default_opus_model: Option<String>,
    pub default_sonnet_model: Option<String>,
    pub default_haiku_model: Option<String>,
    pub model: Option<String>,
    pub subagent_model: Option<String>,
    #[serde(default)]
    pub extras: Vec<String>,
}

impl Default for LightweightEnv {
    fn default() -> Self {
        LightweightEnv {
            auth_token: None,
            base_url: None,
            default_opus_model: None,
            default_sonnet_model: None,
            default_haiku_model: None,
            model: None,
            subagent_model: None,
            extras: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    /// Stable unique identifier (UUID v4).
    #[serde(default)]
    pub id: String,
    /// Display name — any characters (Chinese, spaces, etc.).
    pub name: String,
    /// Short CLI-friendly name (alphanumeric, hyphens, underscores). Optional.
    #[serde(default)]
    pub alias: Option<String>,
    pub added: DateTime<Utc>,
    pub last_used: Option<DateTime<Utc>>,
    #[serde(default)]
    pub kind: ProfileKind,
    #[serde(default)]
    pub env: Option<LightweightEnv>,
    /// Extra CLI args to pass to `claude` on launch (e.g. `--dangerously-skip-permissions`).
    #[serde(default)]
    pub launch_args: Option<Vec<String>>,
}

impl Profile {
    /// Filesystem-safe directory name for this profile's data.
    pub fn dir_name(&self) -> &str {
        self.alias.as_deref().unwrap_or(&self.name)
    }
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Registry {
    /// Keyed by profile `id` (UUID).
    pub profiles: HashMap<String, Profile>,
}

// ── ProfileManager ────────────────────────────────────────────────────────────

#[cfg(target_os = "windows")]
const CMD_MARKER: &str = ":: Generated by cswitch (claude-switch) — do not edit manually";

pub struct ProfileManager {
    pub profiles_dir: PathBuf,
    registry_path: PathBuf,
}

impl ProfileManager {
    pub fn new() -> Result<Self> {
        let home = dirs::home_dir().context("Cannot determine home directory")?;
        let base_dir = home.join(".claude-switch");
        let profiles_dir = base_dir.join("profiles");
        let registry_path = base_dir.join("registry.json");
        fs::create_dir_all(&profiles_dir)?;
        Ok(Self { profiles_dir, registry_path })
    }

    // ── Registry I/O ─────────────────────────────────────────────────────────

    pub fn load_registry(&self) -> Result<Registry> {
        if !self.registry_path.exists() {
            return Ok(Registry::default());
        }
        let content = fs::read_to_string(&self.registry_path)?;
        Ok(serde_json::from_str(&content)?)
    }

    fn save_registry(&self, registry: &Registry) -> Result<()> {
        let content = serde_json::to_string_pretty(registry)?;
        fs::write(&self.registry_path, content)?;
        Ok(())
    }

    /// Update just the launch_args field for a profile.
    pub fn set_launch_args(&self, query: &str, args: Option<Vec<String>>) -> Result<()> {
        let (id, _) = self.find_profile(query)?;
        let mut registry = self.load_registry()?;
        if let Some(p) = registry.profiles.get_mut(&id) {
            p.launch_args = args;
        }
        self.save_registry(&registry)
    }

    // ── Lookup helpers ───────────────────────────────────────────────────────

    /// Find a profile by id, alias, or name (exact match, in that order).
    /// Returns `(id, profile)`.
    pub fn find_profile(&self, query: &str) -> Result<(String, Profile)> {
        let registry = self.load_registry()?;
        if query.is_empty() {
            bail!("Profile query is empty.");
        }

        // 1. Exact match on id
        if let Some(p) = registry.profiles.get(query) {
            return Ok((query.to_string(), p.clone()));
        }

        // 2. Exact match on alias
        let by_alias: Vec<_> = registry
            .profiles
            .iter()
            .filter(|(_, p)| p.alias.as_deref() == Some(query))
            .collect();
        if by_alias.len() == 1 {
            return Ok((by_alias[0].0.clone(), by_alias[0].1.clone()));
        } else if by_alias.len() > 1 {
            bail!(
                "Multiple profiles match alias '{}'. Use the full id to disambiguate.",
                query
            );
        }

        // 3. Exact match on name
        let by_name: Vec<_> = registry
            .profiles
            .iter()
            .filter(|(_, p)| p.name == query)
            .collect();
        if by_name.len() == 1 {
            return Ok((by_name[0].0.clone(), by_name[0].1.clone()));
        } else if by_name.len() > 1 {
            bail!(
                "Multiple profiles match name '{}'. Use an alias or id to disambiguate.",
                query
            );
        }

        bail!(
            "Profile '{}' not found. Add it with: cswitch add <name>",
            query
        )
    }

    /// Check that `name` and `alias` are not already in use by another profile.
    /// `exclude_id` — the profile being edited (don't check against itself).
    pub fn check_unique(&self, exclude_id: &str, name: &str, alias: Option<&str>) -> Result<()> {
        let registry = self.load_registry()?;
        for (id, p) in &registry.profiles {
            if id == exclude_id {
                continue;
            }
            if p.name == name {
                bail!("Profile name '{}' is already in use.", name);
            }
            if let Some(ref a) = p.alias {
                if Some(a.as_str()) == alias {
                    bail!("Alias '{}' is already in use.", a);
                }
            }
        }
        Ok(())
    }

    fn validate_alias(alias: &str) -> Result<()> {
        if !alias
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            bail!(
                "Alias '{}' is invalid. Use only a-z, 0-9, hyphens, and underscores.",
                alias
            );
        }
        Ok(())
    }

    // ── Public CRUD ──────────────────────────────────────────────────────────

    pub fn list_profiles(&self) -> Result<Vec<Profile>> {
        let registry = self.load_registry()?;
        let mut profiles: Vec<Profile> = registry.profiles.into_values().collect();
        profiles.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(profiles)
    }

    pub fn get_profile(&self, query: &str) -> Result<Profile> {
        self.find_profile(query).map(|(_, p)| p)
    }

    /// Full profile: copy `src` into `profiles/<dir_name>`.
    pub fn add_profile_from(&self, name: &str, alias: Option<&str>, src: &Path) -> Result<Profile> {
        if !src.exists() {
            bail!("Source directory '{}' does not exist.", src.display());
        }
        if name.trim().is_empty() {
            bail!("Profile name cannot be empty.");
        }
        self.check_unique("", name, alias)?;
        if let Some(a) = alias {
            Self::validate_alias(a)?;
        }
        let id = Uuid::new_v4().to_string();
        let profile = self.copy_and_build_profile(&id, name, alias, src)?;
        self.upsert_profile(&profile)?;
        Ok(profile)
    }

    /// Force-add: overwrite any conflicting profile (same name or alias).
    pub fn add_profile_from_force(
        &self,
        name: &str,
        alias: Option<&str>,
        src: &Path,
    ) -> Result<Profile> {
        if !src.exists() {
            bail!("Source directory '{}' does not exist.", src.display());
        }
        if name.trim().is_empty() {
            bail!("Profile name cannot be empty.");
        }
        if let Some(a) = alias {
            Self::validate_alias(a)?;
        }

        // Remove conflicting profiles
        let registry = self.load_registry()?;
        for (id, p) in &registry.profiles {
            if p.name == name || p.alias.as_deref() == alias {
                let dir = self.profiles_dir.join(p.dir_name());
                if dir.exists() {
                    let _ = fs::remove_dir_all(&dir);
                }
                let mut reg = self.load_registry()?;
                reg.profiles.remove(id);
                self.save_registry(&reg)?;
            }
        }

        let id = Uuid::new_v4().to_string();
        let profile = self.copy_and_build_profile(&id, name, alias, src)?;
        self.upsert_profile(&profile)?;
        Ok(profile)
    }

    /// Add current `~/.claude` as a full profile.
    pub fn add_profile(&self, name: &str, alias: Option<&str>) -> Result<Profile> {
        let home = dirs::home_dir().context("Cannot determine home directory")?;
        let src = home.join(".claude");
        if !src.exists() {
            bail!("~/.claude does not exist. Is Claude Code installed and logged in?");
        }
        self.add_profile_from(name, alias, &src)
    }

    /// Force-add current `~/.claude` as a full profile.
    pub fn add_profile_force(&self, name: &str, alias: Option<&str>) -> Result<Profile> {
        let home = dirs::home_dir().context("Cannot determine home directory")?;
        let src = home.join(".claude");
        self.add_profile_from_force(name, alias, &src)
    }

    /// Refresh a full profile's data from `~/.claude` (preserves id, name, alias).
    pub fn refresh_profile(&self, query: &str) -> Result<Profile> {
        let (id, profile) = self.find_profile(query)?;
        if profile.kind != ProfileKind::Full {
            bail!("Refresh applies only to full profiles.");
        }
        let home = dirs::home_dir().context("Cannot determine home directory")?;
        let src = home.join(".claude");
        if !src.exists() {
            bail!("~/.claude does not exist.");
        }
        let dir = self.profiles_dir.join(profile.dir_name());
        if dir.exists() {
            fs::remove_dir_all(&dir)?;
        }
        copy_dir_all(&src, &dir)?;

        let mut registry = self.load_registry()?;
        if let Some(p) = registry.profiles.get_mut(&id) {
            p.added = Utc::now();
        }
        self.save_registry(&registry)?;
        Ok(profile)
    }

    pub fn remove_profile(&self, query: &str) -> Result<()> {
        let (id, profile) = self.find_profile(query)?;
        let dir = self.profiles_dir.join(profile.dir_name());
        if profile.kind == ProfileKind::Full && dir.exists() {
            fs::remove_dir_all(&dir)?;
        }
        let mut registry = self.load_registry()?;
        registry.profiles.remove(&id);
        self.save_registry(&registry)
    }

    /// Rename a profile (change name and/or alias). Checks uniqueness.
    pub fn rename_profile(
        &self,
        query: &str,
        new_name: &str,
        new_alias: Option<&str>,
    ) -> Result<Profile> {
        let (id, mut profile) = self.find_profile(query)?;
        if new_name.trim().is_empty() {
            bail!("Profile name cannot be empty.");
        }
        self.check_unique(&id, new_name, new_alias)?;
        if let Some(a) = new_alias {
            Self::validate_alias(a)?;
        }

        let old_dir_name = profile.dir_name().to_string();
        profile.name = new_name.to_string();
        profile.alias = new_alias.map(String::from);
        let new_dir_name = profile.dir_name().to_string();

        // Rename directory if it changed (full profiles)
        if old_dir_name != new_dir_name {
            let old_dir = self.profiles_dir.join(&old_dir_name);
            let new_dir = self.profiles_dir.join(&new_dir_name);
            if old_dir.exists() {
                if new_dir.exists() {
                    fs::remove_dir_all(&new_dir)?;
                }
                fs::rename(&old_dir, &new_dir)?;
            }
        }

        let mut registry = self.load_registry()?;
        registry.profiles.insert(id.clone(), profile.clone());
        self.save_registry(&registry)?;
        Ok(profile)
    }

    pub fn profile_dir(&self, profile: &Profile) -> PathBuf {
        self.profiles_dir.join(profile.dir_name())
    }

    // ── Lightweight profiles ─────────────────────────────────────────────────

    pub fn create_lightweight_profile(
        &self,
        name: &str,
        alias: Option<&str>,
        env: LightweightEnv,
    ) -> Result<Profile> {
        if name.trim().is_empty() {
            bail!("Profile name cannot be empty.");
        }
        self.check_unique("", name, alias)?;
        if let Some(a) = alias {
            Self::validate_alias(a)?;
        }
        let id = Uuid::new_v4().to_string();
        let profile = Profile {
            id,
            name: name.to_string(),
            alias: alias.map(String::from),
            added: Utc::now(),
            last_used: None,
            kind: ProfileKind::Lightweight,
            env: Some(env),
            launch_args: None,
        };
        let mut registry = self.load_registry()?;
        registry.profiles.insert(profile.id.clone(), profile.clone());
        self.save_registry(&registry)?;
        Ok(profile)
    }

    /// Update name, alias, and env vars for an existing lightweight profile.
    pub fn update_lightweight(
        &self,
        query: &str,
        new_name: &str,
        new_alias: Option<&str>,
        env: LightweightEnv,
    ) -> Result<Profile> {
        let (id, existing) = self.find_profile(query)?;
        if new_name.trim().is_empty() {
            bail!("Profile name cannot be empty.");
        }
        self.check_unique(&id, new_name, new_alias)?;
        if let Some(a) = new_alias {
            Self::validate_alias(a)?;
        }

        let profile = Profile {
            id,
            name: new_name.to_string(),
            alias: new_alias.map(String::from),
            added: existing.added,
            last_used: existing.last_used,
            kind: ProfileKind::Lightweight,
            env: Some(env),
            launch_args: existing.launch_args.clone(),
        };

        let mut registry = self.load_registry()?;
        registry.profiles.insert(profile.id.clone(), profile.clone());
        self.save_registry(&registry)?;
        Ok(profile)
    }

    // ── Launch ───────────────────────────────────────────────────────────────

    pub fn launch_claude(&self, query: &str, args: &[String], use_stored_args: bool) -> Result<()> {
        let (id, profile) = self.find_profile(query)?;

        // Update last_used
        let mut registry = self.load_registry()?;
        if let Some(p) = registry.profiles.get_mut(&id) {
            p.last_used = Some(Utc::now());
        }
        self.save_registry(&registry)?;

        let mut cmd = std::process::Command::new("claude");
        if use_stored_args {
            if let Some(ref stored) = profile.launch_args {
                cmd.args(stored);
            }
        }
        cmd.args(args);

        if profile.kind == ProfileKind::Lightweight {
            if let Some(ref env) = profile.env {
                let mut settings = serde_json::Map::new();
                let mut env_map = serde_json::Map::new();

                if let Some(ref t) = env.auth_token {
                    env_map.insert("ANTHROPIC_AUTH_TOKEN".into(), serde_json::Value::String(t.clone()));
                }
                if let Some(ref u) = env.base_url {
                    env_map.insert("ANTHROPIC_BASE_URL".into(), serde_json::Value::String(u.clone()));
                }
                if let Some(ref m) = env.default_opus_model {
                    env_map.insert("ANTHROPIC_DEFAULT_OPUS_MODEL".into(), serde_json::Value::String(m.clone()));
                }
                if let Some(ref m) = env.default_sonnet_model {
                    env_map.insert("ANTHROPIC_DEFAULT_SONNET_MODEL".into(), serde_json::Value::String(m.clone()));
                }
                if let Some(ref m) = env.default_haiku_model {
                    env_map.insert("ANTHROPIC_DEFAULT_HAIKU_MODEL".into(), serde_json::Value::String(m.clone()));
                }
                if let Some(ref m) = env.model {
                    env_map.insert("ANTHROPIC_MODEL".into(), serde_json::Value::String(m.clone()));
                }
                if let Some(ref m) = env.subagent_model {
                    env_map.insert("CLAUDE_CODE_SUBAGENT_MODEL".into(), serde_json::Value::String(m.clone()));
                }
                for extra in &env.extras {
                    if let Some((k, v)) = extra.split_once('=') {
                        env_map.insert(
                            k.trim().to_string(),
                            serde_json::Value::String(v.trim().to_string()),
                        );
                    }
                }

                settings.insert("env".into(), serde_json::Value::Object(env_map));
                let settings_json =
                    serde_json::to_string(&settings).context("Failed to serialize settings JSON")?;
                cmd.arg("--settings");
                cmd.arg(&settings_json);
            }
        } else {
            let profile_dir = self.profile_dir(&profile);
            if !profile_dir.exists() {
                bail!(
                    "Profile directory for '{}' not found. Re-add it with: cswitch add --full {}",
                    profile.name,
                    profile.name
                );
            }
            cmd.env("CLAUDE_CONFIG_DIR", &profile_dir);
        }

        let status = cmd
            .status()
            .context("Failed to launch claude. Is it installed and in your PATH?")?;
        std::process::exit(status.code().unwrap_or(0));
    }

    // ── Aliases ──────────────────────────────────────────────────────────────

    #[cfg(target_os = "windows")]
    pub fn generate_aliases(&self) -> Result<String> {
        let profiles = self.list_profiles()?;
        // Always sync — even when empty (cleans up stale .cmd files)
        let cmd_report = self.sync_cmd_aliases()?;
        if profiles.is_empty() {
            return Ok(format!(
                "# No profiles found. Add one with: cswitch add <name>\n\n{}",
                cmd_report
            ));
        }
        let ps = self.generate_powershell_aliases(&profiles)?;
        Ok(format!("{}\n\n{}", ps, cmd_report))
    }

    #[cfg(not(target_os = "windows"))]
    pub fn generate_aliases(&self) -> Result<String> {
        let profiles = self.list_profiles()?;
        if profiles.is_empty() {
            return Ok("# No profiles found. Add one with: cswitch add <name>".to_string());
        }
        self.generate_shell_aliases_with_bashrc_d(&profiles)
    }

    #[cfg(not(target_os = "windows"))]
    fn generate_shell_aliases_with_bashrc_d(&self, profiles: &[Profile]) -> Result<String> {
        use dirs::home_dir;

        let aliases_content = self.generate_shell_aliases(profiles)?;
        let home = home_dir().context("Cannot determine home directory")?;
        let bashrc_d = home.join(".bashrc.d");

        if bashrc_d.exists() && bashrc_d.is_dir() {
            fs::create_dir_all(&bashrc_d)?;
            let alias_file = bashrc_d.join("38-claude-switch.sh");
            fs::write(&alias_file, &aliases_content)?;
            Ok(format!(
                "{}\n\n# Aliases written to: ~/.bashrc.d/38-claude-switch.sh",
                aliases_content
            ))
        } else {
            Ok(aliases_content)
        }
    }

    #[cfg(not(target_os = "windows"))]
    fn generate_shell_aliases(&self, profiles: &[Profile]) -> Result<String> {
        let mut lines = vec![
            "# claude-switch aliases — auto-generated by `cswitch aliases`".to_string(),
            String::new(),
        ];
        for p in profiles {
            if p.kind == ProfileKind::Lightweight {
                lines.push(format!("# Profile '{}' (lightweight): use 'cswitch use {}'", p.name, p.name));
                continue;
            }
            let dir = self.profile_dir(p);
            let alias_name = p.alias.as_deref().unwrap_or(&p.name);
            lines.push(format!(
                "alias claude-{}=\"CLAUDE_CONFIG_DIR='{}' claude\"",
                alias_name,
                dir.display(),
            ));
        }
        Ok(lines.join("\n"))
    }

    fn generate_powershell_aliases(&self, profiles: &[Profile]) -> Result<String> {
        let mut lines = vec![
            "# claude-switch aliases — add to your PowerShell profile".to_string(),
            "# Run: notepad $PROFILE  to edit your profile".to_string(),
            "# Generated by: cswitch aliases".to_string(),
            String::new(),
        ];
        for p in profiles {
            if p.kind == ProfileKind::Lightweight {
                lines.push(format!(
                    "# Profile '{}' (lightweight): set env vars before running claude",
                    p.name
                ));
                continue;
            }
            let dir = self.profile_dir(p);
            let alias_name = p.alias.as_deref().unwrap_or(&p.name);
            lines.push(format!(
                "function claude-{} {{ $env:CLAUDE_CONFIG_DIR='{}'; claude @args }}",
                alias_name,
                dir.display(),
            ));
        }
        Ok(lines.join("\n"))
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    #[cfg(target_os = "windows")]
    fn cmd_bin_dir() -> Result<PathBuf> {
        let home = dirs::home_dir().context("Cannot determine home directory")?;
        Ok(home.join(".local").join("bin"))
    }

    /// Escape a value for use inside `set "VAR=..."` in a CMD batch file.
    /// Only `%` needs doubling; `"` can't appear inside the quoted form.
    #[cfg(target_os = "windows")]
    fn escape_cmd_set_value(s: &str) -> String {
        s.replace('%', "%%")
    }

    /// Generate the content of a self-contained `.cmd` file for a profile.
    #[cfg(target_os = "windows")]
    fn generate_cmd_content(&self, profile: &Profile) -> Result<String> {
        let kind_label = if profile.kind == ProfileKind::Full { "full" } else { "lightweight" };
        let has_launch = profile.launch_args.as_ref().map_or(false, |a| !a.is_empty());

        let mut lines: Vec<String> = Vec::new();

        lines.push("@echo off".into());
        lines.push("setlocal".into());
        lines.push(CMD_MARKER.into());
        lines.push(format!(":: Profile: {} ({})", profile.name, kind_label));

        // Env vars / config dir (set before delayed expansion to avoid ! issues)
        if profile.kind == ProfileKind::Full {
            let dir = self.profile_dir(profile);
            lines.push(format!("set \"CLAUDE_CONFIG_DIR={}\"", dir.display()));
        } else if let Some(ref env) = profile.env {
            if let Some(ref t) = env.auth_token {
                lines.push(format!(
                    "set \"ANTHROPIC_AUTH_TOKEN={}\"",
                    Self::escape_cmd_set_value(t)
                ));
            }
            if let Some(ref u) = env.base_url {
                lines.push(format!(
                    "set \"ANTHROPIC_BASE_URL={}\"",
                    Self::escape_cmd_set_value(u)
                ));
            }
            if let Some(ref m) = env.default_opus_model {
                lines.push(format!(
                    "set \"ANTHROPIC_DEFAULT_OPUS_MODEL={}\"",
                    Self::escape_cmd_set_value(m)
                ));
            }
            if let Some(ref m) = env.default_sonnet_model {
                lines.push(format!(
                    "set \"ANTHROPIC_DEFAULT_SONNET_MODEL={}\"",
                    Self::escape_cmd_set_value(m)
                ));
            }
            if let Some(ref m) = env.default_haiku_model {
                lines.push(format!(
                    "set \"ANTHROPIC_DEFAULT_HAIKU_MODEL={}\"",
                    Self::escape_cmd_set_value(m)
                ));
            }
            if let Some(ref m) = env.model {
                lines.push(format!(
                    "set \"ANTHROPIC_MODEL={}\"",
                    Self::escape_cmd_set_value(m)
                ));
            }
            if let Some(ref m) = env.subagent_model {
                lines.push(format!(
                    "set \"CLAUDE_CODE_SUBAGENT_MODEL={}\"",
                    Self::escape_cmd_set_value(m)
                ));
            }
            for extra in &env.extras {
                if let Some((k, v)) = extra.split_once('=') {
                    lines.push(format!(
                        "set \"{}={}\"",
                        k.trim(),
                        Self::escape_cmd_set_value(v.trim())
                    ));
                }
            }
        }

        if has_launch {
            let args_str = profile.launch_args.as_ref().unwrap().join(" ");
            lines.push(format!("set \"_LAUNCH_ARGS={}\"", args_str));
        }

        // Delayed expansion enabled here — after all env-var sets — so `!` in
        // values is safe.  Only `_E` and `_R` are used with `!` expansion.
        lines.push("setlocal enabledelayedexpansion".into());
        lines.push("set \"_E=\" & set \"_R=\"".into());
        lines.push(":loop".into());
        lines.push("if \"%~1\"==\"\" goto launch".into());
        lines.push("if /i \"%~1\"==\"-e\" (set \"_E=1\" & shift & goto :loop)".into());
        lines.push("if /i \"%~1\"==\"--extra\" (set \"_E=1\" & shift & goto :loop)".into());
        lines.push("set \"_R=!_R! %1\" & shift & goto :loop".into());
        lines.push(":launch".into());

        // Build the claude command invocation
        if has_launch {
            lines.push(
                "if defined _E (claude %_LAUNCH_ARGS%!_R!) else (claude !_R!)".into(),
            );
        } else {
            lines.push("claude !_R!".into());
        }

        Ok(lines.join("\r\n") + "\r\n")
    }

    /// Synchronize self-contained `.cmd` aliases into `~/.local/bin`.
    /// Creates new files, updates existing ones, and removes stale files
    /// whose profiles no longer exist.
    #[cfg(target_os = "windows")]
    pub fn sync_cmd_aliases(&self) -> Result<String> {
        let profiles = self.list_profiles()?;
        let bin_dir = Self::cmd_bin_dir()?;
        fs::create_dir_all(&bin_dir)?;

        let mut written: std::collections::HashSet<String> = std::collections::HashSet::new();
        let mut report = Vec::new();

        for p in &profiles {
            let alias_name = p.alias.as_deref().unwrap_or(&p.name);
            let cmd_name = format!("claude-{}.cmd", alias_name);
            let cmd_path = bin_dir.join(&cmd_name);
            let content = self.generate_cmd_content(p)?;
            let needs_write = match fs::read_to_string(&cmd_path) {
                Ok(existing) => existing != content,
                Err(_) => true,
            };
            if needs_write {
                fs::write(&cmd_path, &content)?;
                report.push(format!("  + {}", cmd_path.display()));
            } else {
                report.push(format!("  = {}", cmd_path.display()));
            }
            written.insert(cmd_name.to_lowercase());
        }

        // Remove stale cmd files (have marker but no matching profile)
        if let Ok(entries) = fs::read_dir(&bin_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().map_or(false, |e| e == "cmd") {
                    let fname = path.file_name().unwrap().to_string_lossy().to_lowercase();
                    if !written.contains(&fname) {
                        // Check for marker before removing
                        if let Ok(content) = fs::read_to_string(&path) {
                            if content.contains(CMD_MARKER) {
                                let _ = fs::remove_file(&path);
                                report.push(format!("  - {} (stale)", path.display()));
                            }
                        }
                    }
                }
            }
        }

        let bin_str = bin_dir.display().to_string();
        Ok(format!(
            "# CMD aliases synced to {} ({} profiles)\n{}",
            bin_str,
            profiles.len(),
            report.join("\n")
        ))
    }

    fn copy_and_build_profile(
        &self,
        id: &str,
        name: &str,
        alias: Option<&str>,
        src: &Path,
    ) -> Result<Profile> {
        let dir_name = alias.unwrap_or(name);
        let dest = self.profiles_dir.join(dir_name);
        copy_dir_all(src, &dest)?;
        Ok(Profile {
            id: id.to_string(),
            name: name.to_string(),
            alias: alias.map(String::from),
            added: Utc::now(),
            last_used: None,
            kind: ProfileKind::Full,
            env: None,
            launch_args: None,
        })
    }

    fn upsert_profile(&self, profile: &Profile) -> Result<()> {
        let mut registry = self.load_registry()?;
        registry.profiles.insert(profile.id.clone(), profile.clone());
        self.save_registry(&registry)
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst)?;
    let dir = match fs::read_dir(src) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("Warning: cannot read '{}': {}", src.display(), e);
            return Ok(());
        }
    };
    for entry in dir {
        let entry = match entry {
            Ok(e) => e,
            Err(e) => {
                eprintln!("Warning: cannot read entry in '{}': {}", src.display(), e);
                continue;
            }
        };
        let dest_path = dst.join(entry.file_name());

        let is_symlink = entry
            .path()
            .symlink_metadata()
            .map(|m| m.file_type().is_symlink())
            .unwrap_or(false);

        if is_symlink {
            if let Ok(target) = fs::read_link(&entry.path()) {
                if !copy_symlink(&target, &dest_path) {
                    if target.is_dir() {
                        copy_dir_all(&target, &dest_path)?;
                    } else if let Err(e) = fs::copy(&target, &dest_path) {
                        eprintln!("Warning: cannot copy '{}': {}", entry.path().display(), e);
                    }
                }
            }
            continue;
        }

        let file_type = match entry.file_type() {
            Ok(ft) => ft,
            Err(e) => {
                eprintln!("Warning: cannot stat '{}': {}", entry.path().display(), e);
                continue;
            }
        };

        if file_type.is_dir() {
            copy_dir_all(&entry.path(), &dest_path)?;
        } else if let Err(e) = fs::copy(entry.path(), &dest_path) {
            eprintln!("Warning: cannot copy '{}': {}", entry.path().display(), e);
        }
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn copy_symlink(target: &Path, dest: &Path) -> bool {
    use std::os::windows::fs::{symlink_dir, symlink_file};
    let result = if target.is_dir() {
        symlink_dir(target, dest)
    } else {
        symlink_file(target, dest)
    };
    result.is_ok()
}

#[cfg(not(target_os = "windows"))]
fn copy_symlink(target: &Path, dest: &Path) -> bool {
    std::os::unix::fs::symlink(target, dest).is_ok()
}

/// Fetch available model IDs from an OpenAI-compatible /v1/models endpoint.
pub fn fetch_models(base_url: &str, auth_token: &str) -> Result<Vec<String>> {
    let url = format!("{}/v1/models", base_url.trim_end_matches('/'));
    let resp = ureq::get(&url)
        .header("Authorization", &format!("Bearer {}", auth_token))
        .call()
        .context("Failed to fetch models from API")?;
    let json: serde_json::Value = resp
        .into_body()
        .read_json()
        .context("Invalid JSON response from /v1/models")?;
    let data = json
        .get("data")
        .and_then(|d| d.as_array())
        .context("Unexpected response format from /v1/models (missing 'data' array)")?;
    let models: Vec<String> = data
        .iter()
        .filter_map(|entry| entry.get("id").and_then(|id| id.as_str()).map(String::from))
        .collect();
    Ok(models)
}

// ══════════════════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════════════════
#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    // ── Test helpers ──────────────────────────────────────────────────────────

    fn make_manager(tmp: &TempDir) -> ProfileManager {
        let base_dir = tmp.path().join(".claude-switch");
        let profiles_dir = base_dir.join("profiles");
        let registry_path = base_dir.join("registry.json");
        fs::create_dir_all(&profiles_dir).unwrap();
        ProfileManager { profiles_dir, registry_path }
    }

    fn make_claude_dir(root: &Path) -> PathBuf {
        let dir = root.to_path_buf();
        fs::create_dir_all(&dir).unwrap();
        let claude_json = serde_json::json!({
            "oauthAccount": {
                "emailAddress": "test@example.com",
                "accountUuid": "uuid-0000-test"
            },
            "someOtherConfig": true
        });
        fs::write(
            dir.join(".claude.json"),
            serde_json::to_string_pretty(&claude_json).unwrap(),
        )
        .unwrap();
        let creds_json = serde_json::json!({
            "claudeAiOauth": {
                "accessToken": "access_tok",
                "refreshToken": "refresh_tok",
                "expiresAt": 9_999_999_999_u64,
                "scopes": ["user:inference"],
                "subscriptionType": "max"
            }
        });
        fs::write(
            dir.join(".credentials.json"),
            serde_json::to_string_pretty(&creds_json).unwrap(),
        )
        .unwrap();
        dir
    }

    // ── copy_dir_all ──────────────────────────────────────────────────────────

    #[test]
    fn copy_dir_all_copies_flat_files() {
        let tmp = TempDir::new().unwrap();
        let src = tmp.path().join("src");
        fs::create_dir_all(&src).unwrap();
        fs::write(src.join("a.txt"), "hello").unwrap();
        fs::write(src.join("b.txt"), "world").unwrap();
        let dst = tmp.path().join("dst");
        copy_dir_all(&src, &dst).unwrap();
        assert_eq!(fs::read_to_string(dst.join("a.txt")).unwrap(), "hello");
        assert_eq!(fs::read_to_string(dst.join("b.txt")).unwrap(), "world");
    }

    #[test]
    fn copy_dir_all_copies_nested_directories() {
        let tmp = TempDir::new().unwrap();
        let src = tmp.path().join("src");
        fs::create_dir_all(src.join("sub/deep")).unwrap();
        fs::write(src.join("root.txt"), "root").unwrap();
        fs::write(src.join("sub").join("mid.txt"), "mid").unwrap();
        fs::write(src.join("sub/deep").join("leaf.txt"), "leaf").unwrap();
        let dst = tmp.path().join("dst");
        copy_dir_all(&src, &dst).unwrap();
        assert_eq!(fs::read_to_string(dst.join("root.txt")).unwrap(), "root");
        assert_eq!(fs::read_to_string(dst.join("sub/mid.txt")).unwrap(), "mid");
        assert_eq!(fs::read_to_string(dst.join("sub/deep/leaf.txt")).unwrap(), "leaf");
    }

    // ── add_profile_from ──────────────────────────────────────────────────────

    #[test]
    fn load_registry_returns_empty_when_file_absent() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let reg = mgr.load_registry().unwrap();
        assert!(reg.profiles.is_empty());
    }

    #[test]
    fn save_and_load_registry_round_trips() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let id = Uuid::new_v4().to_string();
        let mut reg = Registry::default();
        reg.profiles.insert(
            id.clone(),
            Profile {
                id,
                name: "work".into(),
                alias: None,
                added: Utc::now(),
                last_used: None,
                kind: ProfileKind::Full,
                env: None,
            launch_args: None,
            },
        );
        mgr.save_registry(&reg).unwrap();
        let loaded = mgr.load_registry().unwrap();
        assert_eq!(loaded.profiles.len(), 1);
    }

    // ── add_profile_from ──────────────────────────────────────────────────────

    #[test]
    fn add_profile_copies_files_into_profiles_dir() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        mgr.add_profile_from("work", None, &src).unwrap();
        let profile = mgr.get_profile("work").unwrap();
        let dest = mgr.profile_dir(&profile);
        assert!(dest.join(".claude.json").exists(), ".claude.json missing");
        assert!(dest.join(".credentials.json").exists(), ".credentials.json missing");
    }

    #[test]
    fn add_profile_records_entry_in_registry() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        mgr.add_profile_from("slot", None, &src).unwrap();
        let reg = mgr.load_registry().unwrap();
        let found = reg.profiles.values().any(|p| p.name == "slot");
        assert!(found);
    }

    #[test]
    fn add_profile_errors_on_nonexistent_source() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let err = mgr
            .add_profile_from("bad", None, &tmp.path().join("does-not-exist"))
            .unwrap_err();
        assert!(err.to_string().contains("does not exist"), "{err}");
    }

    #[test]
    fn add_profile_errors_on_duplicate_name() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        mgr.add_profile_from("dup", None, &src).unwrap();
        let err = mgr.add_profile_from("dup", None, &src).unwrap_err();
        assert!(err.to_string().contains("already in use"), "{err}");
    }

    #[test]
    fn add_profile_with_alias() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        let p = mgr.add_profile_from("My Work Profile", Some("work"), &src).unwrap();
        assert_eq!(p.name, "My Work Profile");
        assert_eq!(p.alias.as_deref(), Some("work"));
        // Lookup by alias
        let found = mgr.get_profile("work").unwrap();
        assert_eq!(found.id, p.id);
    }

    // ── find_profile ─────────────────────────────────────────────────────────

    #[test]
    fn find_profile_by_id_alias_name() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        let p = mgr.add_profile_from("Display 名称", Some("short"), &src).unwrap();

        // By id
        let (id, _) = mgr.find_profile(&p.id).unwrap();
        assert_eq!(id, p.id);
        // By alias
        let (id2, _) = mgr.find_profile("short").unwrap();
        assert_eq!(id2, p.id);
        // By name
        let (id3, _) = mgr.find_profile("Display 名称").unwrap();
        assert_eq!(id3, p.id);
        // Not found
        assert!(mgr.find_profile("nope").is_err());
    }

    #[test]
    fn find_profile_errors_on_ambiguous_alias() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let s1 = make_claude_dir(&tmp.path().join("c1"));
        let s2 = make_claude_dir(&tmp.path().join("c2"));
        mgr.add_profile_from("Profile One", Some("p"), &s1).unwrap();
        // Force-add second with same alias should remove the first (force behavior)
        // Actually, add_profile_from checks uniqueness, so second should fail
        let err = mgr.add_profile_from("Profile Two", Some("p"), &s2).unwrap_err();
        assert!(err.to_string().contains("already in use"), "{err}");
    }

    // ── force add ────────────────────────────────────────────────────────────

    #[test]
    fn force_add_overwrites_existing_profile() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("v1"));
        mgr.add_profile_from("slot", None, &src).unwrap();
        let src2 = make_claude_dir(&tmp.path().join("v2"));
        mgr.add_profile_from_force("slot", None, &src2).unwrap();
        let p = mgr.get_profile("slot").unwrap();
        let dest = mgr.profile_dir(&p);
        assert!(dest.join(".claude.json").exists());
    }

    #[test]
    fn force_add_works_when_profile_does_not_yet_exist() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        let p = mgr.add_profile_from_force("brand-new", None, &src).unwrap();
        assert_eq!(p.name, "brand-new");
    }

    // ── list_profiles ─────────────────────────────────────────────────────────

    #[test]
    fn list_profiles_returns_sorted_by_name() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        for name in &["zebra", "alpha", "mango"] {
            let src = make_claude_dir(
                &tmp.path().join(format!("src-{name}")),
            );
            mgr.add_profile_from(name, None, &src).unwrap();
        }
        let profiles = mgr.list_profiles().unwrap();
        let names: Vec<&str> = profiles.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, ["alpha", "mango", "zebra"]);
    }

    // ── remove_profile ────────────────────────────────────────────────────────

    #[test]
    fn remove_profile_by_name_deletes_directory_and_entry() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        let p = mgr.add_profile_from("to-delete", None, &src).unwrap();
        let dir = mgr.profile_dir(&p);
        mgr.remove_profile("to-delete").unwrap();
        assert!(!dir.exists());
        assert!(mgr.get_profile("to-delete").is_err());
    }

    #[test]
    fn remove_profile_by_alias() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        mgr.add_profile_from("Long Display Name", Some("del"), &src).unwrap();
        mgr.remove_profile("del").unwrap();
        assert!(mgr.get_profile("del").is_err());
    }

    #[test]
    fn remove_profile_errors_when_profile_not_found() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let err = mgr.remove_profile("ghost").unwrap_err();
        assert!(err.to_string().contains("not found"), "{err}");
    }

    // ── rename_profile ───────────────────────────────────────────────────────

    #[test]
    fn rename_profile_changes_name_and_alias() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        let p = mgr.add_profile_from("old-name", Some("old"), &src).unwrap();
        let renamed = mgr.rename_profile(&p.id, "new-name", Some("new")).unwrap();
        assert_eq!(renamed.name, "new-name");
        assert_eq!(renamed.alias.as_deref(), Some("new"));
        assert_eq!(renamed.id, p.id); // id preserved
        // Old name no longer works
        assert!(mgr.get_profile("old-name").is_err());
        assert!(mgr.get_profile("old").is_err());
        // New name and alias work
        assert!(mgr.get_profile("new-name").is_ok());
        assert!(mgr.get_profile("new").is_ok());
    }

    #[test]
    fn rename_profile_errors_on_duplicate_name() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let s1 = make_claude_dir(&tmp.path().join("c1"));
        let s2 = make_claude_dir(&tmp.path().join("c2"));
        let p1 = mgr.add_profile_from("Profile A", Some("a"), &s1).unwrap();
        mgr.add_profile_from("Profile B", Some("b"), &s2).unwrap();
        let err = mgr.rename_profile(&p1.id, "Profile B", None).unwrap_err();
        assert!(err.to_string().contains("already in use"), "{err}");
    }

    // ── lightweight profiles ─────────────────────────────────────────────────

    #[test]
    fn create_and_launch_lightweight() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let env = LightweightEnv {
            auth_token: Some("tok".into()),
            base_url: Some("https://api.example.com".into()),
            ..Default::default()
        };
        let p = mgr
            .create_lightweight_profile("lite-prof", Some("lp"), env.clone())
            .unwrap();
        assert_eq!(p.name, "lite-prof");
        assert_eq!(p.alias.as_deref(), Some("lp"));
        assert_eq!(p.kind, ProfileKind::Lightweight);
        // Lookup by alias
        let found = mgr.get_profile("lp").unwrap();
        assert_eq!(found.id, p.id);
    }

    #[test]
    fn update_lightweight_preserves_id() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let env = LightweightEnv {
            auth_token: Some("old".into()),
            ..Default::default()
        };
        let p = mgr
            .create_lightweight_profile("test", Some("t"), env)
            .unwrap();
        let original_id = p.id.clone();

        let new_env = LightweightEnv {
            auth_token: Some("new".into()),
            ..Default::default()
        };
        let updated = mgr
            .update_lightweight(&original_id, "test-renamed", Some("tr"), new_env)
            .unwrap();
        assert_eq!(updated.id, original_id);
        assert_eq!(updated.name, "test-renamed");
        assert_eq!(updated.alias.as_deref(), Some("tr"));
        assert_eq!(updated.env.as_ref().unwrap().auth_token.as_deref(), Some("new"));
    }

    // ── generate_aliases ──────────────────────────────────────────────────────

    #[test]
    fn generate_aliases_uses_alias_when_present() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let src = make_claude_dir(&tmp.path().join("fake-claude"));
        mgr.add_profile_from("Long Name", Some("ln"), &src).unwrap();
        let out = mgr.generate_aliases().unwrap();
        // Should use "ln" (alias) not "Long Name"
        assert!(out.contains("claude-ln"), "expected 'claude-ln' in:\n{out}");
    }

    #[test]
    fn generate_aliases_when_empty_returns_hint() {
        let tmp = TempDir::new().unwrap();
        let mgr = make_manager(&tmp);
        let out = mgr.generate_aliases().unwrap();
        assert!(out.contains("No profiles"), "{out}");
    }
}