use anyhow::{Context, Result, bail};
use chrono::Utc;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use uuid::Uuid;

mod api_test;
mod artifacts;
mod config_bundle;
mod diagnostics;
mod launch;
mod local_shims;
mod mcp;
mod mcp_config;
mod mcp_registry;
mod mcp_secrets;
mod mcp_validation;
mod profiles;
mod providers;
mod remote_alias_sync;
mod remote_sftp;
mod shim_recovery;
mod shims;
mod storage;
mod tinyfish;
mod types;
mod url_match;
pub use self::api_test::*;
use self::tinyfish::{
    TinyfishMode, TinyfishToolShell, build_lightweight_runtime_artifacts,
    build_lightweight_settings_env_prefix, native_tinyfish_tool_shell, tinyfish_available,
    tinyfish_permissions_allowlist,
};
pub use self::types::*;

const CLAUDE_SWITCH_HOME_ENV: &str = "CLAUDE_SWITCH_HOME";

fn escape_cmd_json_fragment(fragment: &str) -> String {
    let mut out = String::with_capacity(fragment.len() * 2);
    for ch in fragment.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '%' => out.push_str("%%"),
            '^' => out.push_str("^^"),
            _ => out.push(ch),
        }
    }
    out
}

fn assign_cmd_json_var(lines: &mut Vec<String>, var_name: &str, json: &str) {
    let escaped = escape_cmd_json_fragment(json);
    lines.push(format!("set \"{var_name}={escaped}\""));
}

// ── ProfileManager ────────────────────────────────────────────────────────────

const CMD_MARKER: &str = ":: Generated by cswitch (claude-switch) — do not edit manually";
const SH_MARKER: &str = "# Generated by cswitch (claude-switch) — do not edit manually";

pub struct ProfileManager {
    pub profiles_dir: PathBuf,
    registry_path: PathBuf,
}

impl ProfileManager {}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn copy_dir_all(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst)?;
    let dir = match fs::read_dir(src) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("Warning: cannot read '{}': {}", src.display(), e);
            return Ok(());
        }
    };
    for entry in dir {
        let entry = match entry {
            Ok(e) => e,
            Err(e) => {
                eprintln!("Warning: cannot read entry in '{}': {}", src.display(), e);
                continue;
            }
        };
        let dest_path = dst.join(entry.file_name());

        let is_symlink = entry
            .path()
            .symlink_metadata()
            .map(|m| m.file_type().is_symlink())
            .unwrap_or(false);

        if is_symlink {
            if let Ok(target) = fs::read_link(entry.path())
                && !copy_symlink(&target, &dest_path)
            {
                if target.is_dir() {
                    copy_dir_all(&target, &dest_path)?;
                } else if let Err(e) = fs::copy(&target, &dest_path) {
                    eprintln!("Warning: cannot copy '{}': {}", entry.path().display(), e);
                }
            }
            continue;
        }

        let file_type = match entry.file_type() {
            Ok(ft) => ft,
            Err(e) => {
                eprintln!("Warning: cannot stat '{}': {}", entry.path().display(), e);
                continue;
            }
        };

        if file_type.is_dir() {
            copy_dir_all(&entry.path(), &dest_path)?;
        } else if let Err(e) = fs::copy(entry.path(), &dest_path) {
            eprintln!("Warning: cannot copy '{}': {}", entry.path().display(), e);
        }
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn copy_symlink(target: &Path, dest: &Path) -> bool {
    use std::os::windows::fs::{symlink_dir, symlink_file};
    let result = if target.is_dir() {
        symlink_dir(target, dest)
    } else {
        symlink_file(target, dest)
    };
    result.is_ok()
}

#[cfg(not(target_os = "windows"))]
fn copy_symlink(target: &Path, dest: &Path) -> bool {
    std::os::unix::fs::symlink(target, dest).is_ok()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RemoteOs {
    Unix,
    Windows,
}

// ══════════════════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════════════════
#[cfg(test)]
mod tests;
